version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: dockerfile-postgres
    ports:
      - 5432:5432